version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - redis-network
    command: redis-server --appendonly yes

  myapp:
    build: .
    container_name: myapp
    depends_on:
      - redis
    environment:
      - REDIS_CONNECTION=redis:6379
    networks:
      - redis-network
    ports:
      - "5000:5000"

networks:
  redis-network:
    driver: bridge
